print('='*20+'계산 프로그램 실행'+'='*20)
print('계산 프로그램이 실행되었습니다')
print('식 작성 양식은 다음과 같습니다.')
print('덧셈 식 = ex) 2+3')
print('뺄셈 식 = ex) 3-1')
print('곱셈 식 = ex) 3*3')
print('나눗셈 식 = ex) 12/6')
number=input('원하는 식을 입력하십시오.')
print('계산 값은 다음과 같습니다 '+number)